name: Pull Request Auto Labeler

on:
  pull_request:
    types: [opened, edited]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: fuxingloh/multi-labeler@v4 # v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} # optional, default to '${{ github.token }}'
          config-path: .github/auto-labeler.yml # optional, default to '.github/labeler.yml'
